kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: "claim3"
  annotations:
    volume.alpha.kubernetes.io/storage-class: "foo"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
